#!/usr/bin/python3.12
"""Generates tests/host/crypto_vectors.h: known-answer vectors for the M5
crypto code (lib/crypto), computed by independent implementations --
Python's hashlib/hmac and the `cryptography` package (OpenSSL backend) --
not by the C code under test.  Deterministic: inputs come from a fixed
seed, so re-running produces the same file except for the signatures,
which are randomised by OpenSSL (ECDSA nonce, PSS salt) and only need to
verify.

This is a development-time tool (it needs `cryptography`, which the bench
does not require); the generated header is committed.  Run:

    python3.12 tests/host/gen_crypto_vectors.py > tests/host/crypto_vectors.h
"""

import hashlib
import hmac
import random

from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import ec, padding, rsa, x25519
from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
from cryptography.hazmat.primitives.ciphers.aead import AESGCM, ChaCha20Poly1305

R = random.Random(20260924)


def rb(n):
    return bytes(R.getrandbits(8) for _ in range(n))


def c_bytes(b):
    if not b:
        return "{0}", 0
    return "{" + ", ".join("0x%02x" % x for x in b) + "}", len(b)


out = []


def arr(name, b):
    body, n = c_bytes(b)
    out.append("static const uint8_t %s[] = %s;" % (name, body))
    out.append("#define %s_LEN %du" % (name.upper(), n))


def hkdf(h, salt, ikm, info, length):
    prk = hmac.new(salt or bytes(h().digest_size), ikm, h).digest()
    okm, t, i = b"", b"", 1
    while len(okm) < length:
        t = hmac.new(prk, t + info + bytes([i]), h).digest()
        okm += t
        i += 1
    return prk, okm[:length]


class HmacDrbg:
    """SP 800-90A HMAC_DRBG (SHA-256), written from the standard."""

    def __init__(self, entropy, pers):
        self.K, self.V = b"\x00" * 32, b"\x01" * 32
        self.update(entropy + pers)

    def update(self, data):
        self.K = hmac.new(self.K, self.V + b"\x00" + data, hashlib.sha256).digest()
        self.V = hmac.new(self.K, self.V, hashlib.sha256).digest()
        if data:
            self.K = hmac.new(self.K, self.V + b"\x01" + data, hashlib.sha256).digest()
            self.V = hmac.new(self.K, self.V, hashlib.sha256).digest()

    def generate(self, n, addl=b""):
        if addl:
            self.update(addl)
        t = b""
        while len(t) < n:
            self.V = hmac.new(self.K, self.V, hashlib.sha256).digest()
            t += self.V
        self.update(addl)
        return t[:n]


def main():
    out.append("/* Generated by tests/host/gen_crypto_vectors.py -- do not edit. */")
    out.append("#include <stdint.h>")
    # hashes
    msgs = [b"", b"abc", rb(111), rb(112), rb(1000)]
    out.append("#define HASH_VECTORS %d" % len(msgs))
    for i, m in enumerate(msgs):
        arr("hash_msg%d" % i, m)
        arr("hash_msg%d_sha256" % i, hashlib.sha256(m).digest())
        arr("hash_msg%d_sha384" % i, hashlib.sha384(m).digest())
        arr("hash_msg%d_sha512" % i, hashlib.sha512(m).digest())
    # HMAC (short and long keys), HKDF
    for i, (klen, mlen) in enumerate([(20, 50), (131, 200)]):
        k, m = rb(klen), rb(mlen)
        arr("hmac%d_key" % i, k)
        arr("hmac%d_msg" % i, m)
        arr("hmac%d_sha256" % i, hmac.new(k, m, hashlib.sha256).digest())
        arr("hmac%d_sha384" % i, hmac.new(k, m, hashlib.sha384).digest())
    salt, ikm, info = rb(13), rb(22), rb(10)
    prk, okm = hkdf(hashlib.sha256, salt, ikm, info, 82)
    arr("hkdf_salt", salt)
    arr("hkdf_ikm", ikm)
    arr("hkdf_info", info)
    arr("hkdf_prk", prk)
    arr("hkdf_okm", okm)
    # HMAC_DRBG
    ent, pers, ent2 = rb(48), rb(16), rb(48)
    d = HmacDrbg(ent, pers)
    g1 = d.generate(40)
    g2 = d.generate(64, b"addl")
    d.update(ent2)  # reseed = update(entropy || additional input), additional empty
    g3 = d.generate(32)
    arr("drbg_entropy", ent)
    arr("drbg_pers", pers)
    arr("drbg_entropy2", ent2)
    arr("drbg_out1", g1)
    arr("drbg_out2", g2)
    arr("drbg_out3", g3)
    # AEADs
    lens = [(0, 0), (13, 1), (0, 15), (20, 16), (5, 17), (32, 100), (0, 300)]
    out.append("#define AEAD_VECTORS %d" % len(lens))
    for i, (alen, plen) in enumerate(lens):
        for name, klen, cls in (("gcm128", 16, AESGCM), ("gcm256", 32, AESGCM),
                                ("chacha", 32, ChaCha20Poly1305)):
            key, nonce, aad, pt = rb(klen), rb(12), rb(alen), rb(plen)
            ct = cls(key).encrypt(nonce, pt, aad or None)
            p = "%s%d" % (name, i)
            arr(p + "_key", key)
            arr(p + "_nonce", nonce)
            arr(p + "_aad", aad)
            arr(p + "_pt", pt)
            arr(p + "_ct", ct)  # ciphertext || tag
    # X25519
    out.append("#define X25519_VECTORS 3")
    for i in range(3):
        a = x25519.X25519PrivateKey.from_private_bytes(rb(32))
        b = x25519.X25519PrivateKey.from_private_bytes(rb(32))
        raw = serialization.Encoding.Raw
        priv = a.private_bytes(raw, serialization.PrivateFormat.Raw,
                               serialization.NoEncryption())
        bpub = b.public_key().public_bytes(raw, serialization.PublicFormat.Raw)
        arr("x25519_%d_scalar" % i, priv)
        arr("x25519_%d_point" % i, bpub)
        arr("x25519_%d_pub" % i, a.public_key().public_bytes(raw, serialization.PublicFormat.Raw))
        arr("x25519_%d_shared" % i, a.exchange(b.public_key()))
    # RSA
    for i, (bits, h, hl) in enumerate([(2048, hashes.SHA256(), 32), (3072, hashes.SHA384(), 48)]):
        k = rsa.generate_private_key(65537, bits)
        pn = k.public_key().public_numbers()
        msg = rb(77)
        arr("rsa%d_n" % i, pn.n.to_bytes(bits // 8, "big"))
        arr("rsa%d_e" % i, pn.e.to_bytes(3, "big"))
        arr("rsa%d_msg" % i, msg)
        arr("rsa%d_pkcs1" % i, k.sign(msg, padding.PKCS1v15(), h))
        arr("rsa%d_pss" % i, k.sign(msg, padding.PSS(padding.MGF1(h), hl), h))
    # ECDSA
    for i, (curve, h) in enumerate([(ec.SECP256R1(), hashes.SHA256()),
                                    (ec.SECP384R1(), hashes.SHA384()),
                                    (ec.SECP256R1(), hashes.SHA384())]):
        k = ec.generate_private_key(curve)
        msg = rb(64)
        sig = k.sign(msg, ec.ECDSA(h))
        r, s = decode_dss_signature(sig)
        size = curve.key_size // 8
        arr("ecdsa%d_pub" % i, k.public_key().public_bytes(
            serialization.Encoding.X962, serialization.PublicFormat.UncompressedPoint))
        arr("ecdsa%d_msg" % i, msg)
        arr("ecdsa%d_der" % i, sig)
        arr("ecdsa%d_r" % i, r.to_bytes(size, "big"))
        arr("ecdsa%d_s" % i, s.to_bytes(size, "big"))
    print("\n".join(out))


if __name__ == "__main__":
    main()
