#!/usr/bin/env python3
"""Generates crates/linux-compat/src/table.rs from the Linux x86-64 system
call table (asm/unistd_64.h), so no number is typed by hand.

    gen_syscalls.py --header /path/to/asm/unistd_64.h [--out FILE] [--check]

`--check` compares the output with the checked-in file instead of writing.
"""
import hashlib
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "..", "crates", "linux-compat", "src", "table.rs")


def parse(text):
    seen = {}
    for m in re.finditer(r"^#define __NR_([a-z0-9_]+)\s+(\d+)\s*$", text, re.M):
        name, nr = m.group(1), int(m.group(2))
        if name == "syscalls":
            continue
        seen.setdefault(nr, name)
    return sorted(seen.items())


def render(table, digest):
    out = [
        "// Generated by tools/linuxcompat/gen_syscalls.py from asm/unistd_64.h",
        "// (sha256 %s). Do not edit." % digest,
        "",
        "#![allow(dead_code)]",
        "",
    ]
    for nr, name in table:
        out.append("pub const SYS_%s: u32 = %d;" % (name.upper(), nr))
    out += ["", "/// Every system call of the table, by number.", "pub static TABLE: [(u32, &str); %d] = [" % len(table)]
    for nr, name in table:
        out.append('    (%d, "%s"),' % (nr, name))
    out += ["];", "", "pub const MAX_NR: u32 = %d;" % table[-1][0], ""]
    return "\n".join(out)


def main():
    args = sys.argv[1:]
    get = lambda k: args[args.index(k) + 1] if k in args else None
    header = get("--header")
    if not header:
        print(__doc__)
        return 2
    raw = open(header, "rb").read()
    table = parse(raw.decode())
    text = render(table, hashlib.sha256(raw).hexdigest())
    out = get("--out") or OUT
    if "--check" in args:
        same = os.path.exists(out) and open(out, encoding="utf-8").read() == text
        print("%s: %s" % (out, "ok" if same else "DIFFERS"))
        return 0 if same else 1
    open(out, "w", encoding="utf-8", newline="\n").write(text)
    print("wrote %s (%d system calls)" % (out, len(table)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
